name = "Pandora"
uuid = "ddb62b48-25b1-445b-9844-d5846bdd42c2"
authors = ["tbrysiewicz <taylorbrysiewicz@gmail.com>"]
version = "0.2.0"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
